from telegram import InlineKeyboardButton, InlineKeyboardMarkup

COINS = {
    "zrx": "0X",
    "1inch": "1Inch",
    "aave": "Aave",
    "elf": "Aelf",
    "aero": "Aerodrome Finance",
    "ai16z": "Ai16Z",
    "aioz": "Aioz Network",
    "akt": "Akash Network",
    "ach": "Alchemy Pay",
    "algo": "Algorand",
    "alt": "Altlayer",
    "amp": "Amp",
    "ankr": "Ankr",
    "ape": "Apecoin",
    "nft": "Nft Protocol",
    "api3": "Api3",
    "apt": "Aptos",
    "ant": "Aragon",
    "arb": "Arbitrum",
    "ardr": "Ardor",
    "arkm": "Arkham",
    "ar": "Arweave",
    "astr": "Astar",
    "asbnb": "Astherus Staked Bnb",
    "audio": "Audius",
    "rep": "Augur",
    "avax": "Avalanche",
    "axl": "Axelar",
    "axs": "Axie Infinity",
    "band": "Band Protocol",
    "bat": "Basic Attention Token",
    "beam": "Beam",
    "bdx": "Beldex",
    "bico": "Biconomy",
    "bnb": "Binance Coin",
    "busd": "Busd",
    "btc": "Bitcoin",
    "bch": "Bitcoin Cash",
    "btg": "Bitcoin Gold",
    "bsv": "Bitcoin Sv",
    "bgb": "Bitget Token",
    "btm": "Bitmark",
    "tao": "Bittensor",
    "btt": "Bittorrent",
    "volt": "Bitvolt",
    "blur": "Blur",
    "bonk": "Bonk",
    "bome": "Book Of Meme",
    "ada": "Cardano",
    "ctsi": "Cartesi",
    "celr": "Celer Network",
    "tia": "Celestia",
    "celo": "Celo",
    "cel": "Celsius",
    "link": "Chainlink",
    "cheel": "Cheelee",
    "chz": "Chiliz",
    "chrm": "Chromia",
    "cvc": "Civic",
    "cocos": "Cocos-Bcx",
    "cbeth": "Coinbase Wrapped Staked Eth",
    "comp": "Compound Coin",
    "cfx": "Conflux Network",
    "people": "Constitutiondao",
    "cvx": "Convex Finance",
    "core": "Core",
    "atom": "Cosmos",
    "coti": "Coti",
    "cro": "Crypto.Com Coin",
    "crv": "Curve Dao Token",
    "dai": "Dai",
    "dash": "Dash",
    "mana": "Decentraland",
    "dcr": "Decred",
    "dfi": "Defichain",
    "dent": "Dent",
    "dexe": "Dexe",
    "dgb": "Digibyte",
    "doge": "Dogecoin",
    "elon": "Dogelon Mars",
    "wif": "Dogwifhat",
    "dydx": "Dydx",
    "dym": "Dymension",
    "xec": "Ecash",
    "prime": "Echelon Prime",
    "egld": "Multiversx",
    "ewt": "Energy Web Token",
    "enj": "Enjin Coin",
    "eos": "Eos",
    "ena": "Ethena",
    "usde": "Ethena Usde",
    "ethfi": "Ether.Fi",
    "eth": "Ethereum",
    "etc": "Ethereum Classic",
    "ens": "Ethereum Name Service",
    "ethw": "Ethereumpow",
    "ever": "Everscale",
    "ftm": "Fantom",
    "ftn": "Fasttoken",
    "fet": "Fetch.Ai",
    "figr_heloc": "Figure Heloc",
    "fil": "Filecoin",
    "fdusd": "First Digital Usd",
    "flr": "Flare",
    "floki": "Floki",
    "flow": "Flow",
    "flux": "Flux",
    "frxeth": "Frax Ether",
    "fxs": "Frax Share",
    "ftt": "Ftx Token",
    "gala": "Gala",
    "gal": "Galxe",
    "gt": "Gatetoken",
    "gusd": "Gemini Dollar",
    "gtc": "Global Tour Coin",
    "gmt": "Gmt",
    "gno": "Gnosis",
    "gnt": "Golem",
    "gfi": "Gravity Finance",
    "one": "Harmony",
    "hbar": "Hedera Hashgraph",
    "hnt": "Helium",
    "hive": "Hive",
    "hot": "Holo",
    "zen": "Horizen",
    "ht": "Huobi Token",
    "icx": "Icon",
    "rlc": "Iexec Rlc",
    "ilv": "Illuvium",
    "imx": "Impact",
    "inj": "Injective Protocol",
    "icp": "Internet Computer",
    "iost": "Iost",
    "miota": "Iota",
    "iotx": "Iotex",
    "jasmy": "Jasmycoin",
    "jto": "Jito",
    "jup": "Jupiter",
    "jst": "Just",
    "kas": "Kaspa",
    "kava": "Kava",
    "keep": "Keep Network",
    "rseth": "Kelp Dao Restaked Eth",
    "klay": "Klaytn",
    "kcs": "Kucoin",
    "ksm": "Kusama",
    "knc": "Kyber Network",
    "leo": "Leo Tokens",
    "ldo": "Lido Dao",
    "steth": "Lido Staked Ether",
    "stsol": "Lido Staked Sol",
    "lsk": "Lisk",
    "ltc": "Litecoin",
    "lpt": "Livepeer",
    "lrc": "Loopring",
    "lyxe": "Lukso",
    "mkr": "Maker",
    "manta": "Manta Network",
    "mnt": "Mantle",
    "meth": "Mantle Staked Ether",
    "om": "Mantra",
    "msol": "Marinade Staked Sol",
    "pond": "Marlin",
    "mask": "Mask Network",
    "mvl": "Mass Vehicle Ledger",
    "mdx": "Mdex",
    "meme": "Memecoin",
    "memecore": "Memecore",
    "mtl": "Metal",
    "metis": "Metis",
    "met": "Metronome",
    "mina": "Mina",
    "mbox": "Mobox",
    "xmr": "Monero",
    "moodeng": "Moo-Deng",
    "glmr": "Moonbeam",
    "mx": "Mx",
    "myx": "Myx Finance",
    "near": "Near Protocol",
    "neiro3": "Neiro-3",
    "xem": "Nem",
    "neo": "Neo",
    "ckb": "Nervos Network",
    "nexo": "Nexo",
    "nos": "Nosana",
    "nmr": "Numeraire",
    "rose": "Oasis Network",
    "ocean": "Ocean Protocol",
    "okb": "Okb",
    "omg": "Omisego",
    "ondo": "Ondo",
    "ong": "Ong.Social",
    "ont": "Ontology",
    "op": "Optimism",
    "orbs": "Orbs",
    "oeth": "Origin Ether",
    "trac": "Origintrail",
    "osmo": "Osmosis",
    "cake": "Pancakeswap",
    "paxg": "Pax Gold",
    "pyusd": "Paypal Usd",
    "pendle": "Pendle",
    "pepe": "Pepe",
    "dot": "Polkadot",
    "matic": "Polygon",
    "poly": "Polymath Network",
    "polyx": "Polymesh",
    "popcat": "Popcat",
    "pump": "Pump.Fun",
    "pundix": "Pundi X[New]",
    "pyth": "Pyth Network",
    "qtum": "Qtum",
    "qnt": "Quant",
    "xrd": "Radix",
    "rvn": "Ravencoin",
    "ray": "Raydium",
    "rekt": "Rekt-4",
    "rndr": "Render Token",
    "rez": "Renzo",
    "req": "Request Network",
    "rsr": "Reserve Rights",
    "resolv-rlp": "Resolv Rlp",
    "rbn": "Ribbon Finance",
    "rpl": "Rocket Pool",
    "ron": "Ronin",
    "sfp": "Safepal",
    "saharaai": "Sahara-Ai",
    "sand": "Sandbox",
    "sats": "Sats (Ordinals)",
    "sdai": "Savings Dai",
    "scrt": "Secretcoin",
    "sei": "Sei",
    "srm": "Serum",
    "shib": "Shiba Inu",
    "sc": "Siacoin",
    "agix": "Singularitynet",
    "skl": "Skale Network",
    "skorai": "Skor-Ai",
    "slp": "Smooth Love Potion",
    "snek": "Snek",
    "sol": "Solana",
    "somi": "Somnia",
    "stx": "Stacks",
    "ethx": "Stader Ethx",
    "sfrxeth": "Staked Frax Ether",
    "strk": "Starknet",
    "snt": "Status",
    "xlm": "Stellar",
    "storj": "Storj",
    "sui": "Sui",
    "super": "Superverse",
    "sushi": "Sushi",
    "sweth": "Swell Ethereum",
    "sxp": "Swipe",
    "chsb": "Swissborg",
    "snx": "Synthetix Network Token",
    "sys": "Syscoin",
    "tdccp": "Tdccp",
    "tel": "Telcoin",
    "luna": "Terra",
    "lunc": "Terra Luna Classic",
    "usdt": "Tether",
    "xaut": "Tether Gold",
    "xtz": "Tezos",
    "grt": "The Graph",
    "tfuel": "Theta Fuel",
    "theta": "Theta Token",
    "rune": "Thorchain",
    "tkx": "Tokenize Xchange",
    "ton": "Toncoin",
    "tribe": "Tribe",
    "trx": "Tron",
    "tusd": "True Usd",
    "twt": "Trust Wallet Token",
    "uma": "Uma",
    "uni": "Uniswap",
    "usdc": "Usd Coin",
    "usdd": "Usdd",
    "usdp": "Usdp Stablecoin",
    "useless3": "Useless-3",
    "vet": "Vechain",
    "velo": "Velo",
    "venom": "Venom",
    "vtho": "Vethor Token",
    "vgx": "Voyager Token",
    "pyr": "Vulcan Forged",
    "waves": "Waves",
    "wemix": "Wemix",
    "wbt": "Whitebit Coin",
    "woo": "Wootrade",
    "wlfi": "World Liberty Financial",
    "wld": "Worldcoin",
    "w": "Wormhole",
    "wbtc": "Wrapped Bitcoin",
    "weeth": "Wrapped Eeth",
    "xdc": "Xdc Network",
    "xrp": "Xrp",
    "yfi": "Yearn.Finance",
    "zano": "Zano",
    "zec": "Zcash",
    "zbcn": "Zebec Network",
    "zeta": "Zetachain",
    "zil": "Zilliqa",
    "zora": "Zora"
}


def main_menu_keyboard():
    return InlineKeyboardMarkup([
        [
            InlineKeyboardButton("📰 Latest News", callback_data="latest"),
            InlineKeyboardButton("₿ Crypto News", callback_data="crypto_menu"),
        ]
    ])


def crypto_coins_keyboard():
    buttons = []
    row = []
    for key, name in COINS.items():
        row.append(InlineKeyboardButton(name, callback_data=f"crypto:{key}"))
        if len(row) == 3:  # 3 buttons per row — adjust as you like
            buttons.append(row)
            row = []
    if row:
        buttons.append(row)

    buttons.append([InlineKeyboardButton("« Back to Main", callback_data="back_main")])

    return InlineKeyboardMarkup(buttons)


def back_to_main_keyboard():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("« Back to Main Menu", callback_data="back_main")]
    ])


def back_to_crypto_keyboard():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("« Back to Coins", callback_data="crypto_menu")]
    ])